### ISSUE TITLE
How to test a server with docker ?

### ISSUE THREAD

**Issue by jonadem** [crossbario/autobahn-testsuite#106]
I tried unluckily: 
`$ sudo docker run -it --rm -v "${PWD}/config:/config" -v "${PWD}/reports:/reports" --name fuzzingclient crossbario/autobahn-testsuite`
And I get : 

    Using explicit spec file '/config/fuzzingserver.json'
    Loading spec from /config/fuzzingserver.json
    Traceback (most recent call last):
    File "/usr/local/bin/wstest", line 11, in <module>
        sys.exit(run())
    File "/usr/local/site-packages/autobahntestsuite/wstest.py", line 337, in run
        spec = json.loads(open(spec_filename).read())
    IOError: [Errno 2] No such file or directory: '/config/fuzzingserver.json'`

In `config/`, I have a `fuzzingclient.json`from [there](https://github.com/crossbario/autobahn-testsuite/blob/master/docker/config/fuzzingclient.json). If I put a `fuzzingserver.json`, it behave like it is testing for clients, which is not why I am looking for.

How can I test a websocket server ?

**Comment by skaarj1989** [comment]
I'm testing my server implementation with:
```bash
docker run -it --rm -v %cd%\config:/config -v %cd%\reports:/reports crossbario/autobahn-testsuite wstest -m fuzzingclient -s /config/fuzzingclient.json
```
It's Windows, so change **%cd%** to **${PWD}**

**fuzzingclient.json**
```json
{
  "options": {},
  "outdir": "./reports/servers",
  "servers": [
    {
      "agent": "AVR / W5100 / Ethernet",
      "url": "ws://192.168.46.180:9001"
    }
  ],
  "cases": [ "*" ],
  "exclude-cases": [],
  "exclude-agent-cases": {}
}
```
