### ISSUE TITLE
ModuleNotFoundError: No module named '_version'

### ISSUE THREAD

**Issue by abhinavsingh** [crossbario/autobahn-testsuite#121]
```console
pip install autobahntestsuite
wstest -h                                                                         ─╯
Traceback (most recent call last):
  File "/Users/abhinavsingh/Dev/proxy.py/venv-wstest/bin/wstest", line 5, in <module>
    from autobahntestsuite.wstest import run
  File "/Users/abhinavsingh/Dev/proxy.py/venv-wstest/lib/python3.9/site-packages/autobahntestsuite/__init__.py", line 19, in <module>
    from _version import __version__
ModuleNotFoundError: No module named '_version'
```

**Comment by essen** [comment]
Same. What's the solution?

**Comment by markmaker** [comment]
Same here.

**Comment by erikolofsson** [comment]
On macOS:
```bash
rm -rf ~/wstest
rm -rf ~/Library/Caches/pip
export BREW_HOME=`brew --prefix`
brew install pyenv
brew install openssl@1.1 --force
pyenv install 2.7.18 -f
pyenv global 2.7.18
PATH="$(pyenv root)/shims:$PATH"
which python
pip install virtualenv
virtualenv ~/wstest
source ~/wstest/bin/activate
python --version
pip install typing
CPPFLAGS="-I${BREW_HOME}/opt/openssl@1.1/include" CFLAGS="-I${BREW_HOME}/opt/openssl@1.1/include" pip install autobahntestsuite
wstest -a
```
