### ISSUE TITLE
Crash when redirecting ws => https

### ISSUE THREAD

**Issue by Etan1** [crossbario/autobahn-testsuite#63]
Crash happens when targeting fuzzingclient at a server that incorrectly redirects `ws://127.0.0.1:8080` to `https://127.0.0.1:8443/`.
System is macOS Sierra.

```
{
   "outdir": "./reports/servers",
   "servers": [
      {
         "url": "ws://127.0.0.1:8080"
      }
   ],
   "cases": ["*"],
   "exclude-cases": [],
   "exclude-agent-cases": {}
}
```

```
Servers = [u'ws://127.0.0.1:8080']
Unhandled Error
Traceback (most recent call last):
File "~/wstest/lib/python2.7/site-packages/autobahntestsuite/wstest.py", line 338, in run
start(options, spec)
File "~/wstest/lib/python2.7/site-packages/autobahntestsuite/wstest.py", line 272, in start
reactor.run()
File "~/wstest/lib/python2.7/site-packages/twisted/internet/base.py", line 1195, in run
self.mainLoop()
File "~/wstest/lib/python2.7/site-packages/twisted/internet/base.py", line 1204, in mainLoop
self.runUntilCurrent()
--- <exception caught here> ---
File "~/wstest/lib/python2.7/site-packages/twisted/internet/base.py", line 825, in runUntilCurrent
call.func(*call.args, **call.kw)
File "~/wstest/lib/python2.7/site-packages/twisted/internet/tcp.py", line 479, in connectionLost
self.connector.connectionLost(reason)
File "~/wstest/lib/python2.7/site-packages/twisted/internet/base.py", line 1088, in connectionLost
self.factory.clientConnectionLost(self, reason)
File "~/wstest/lib/python2.7/site-packages/autobahntestsuite/fuzzing.py", line 1292, in clientConnectionLost
self.createReports()
File "~/wstest/lib/python2.7/site-packages/autobahntestsuite/fuzzing.py", line 469, in createReports
self.createMasterReportHTML(self.outdir)
File "~/wstest/lib/python2.7/site-packages/autobahntestsuite/fuzzing.py", line 670, in createMasterReportHTML
agent_case_report_file = self.makeAgentCaseReportFilename(agentId, caseId, ext = 'html')
File "~/wstest/lib/python2.7/site-packages/autobahntestsuite/fuzzing.py", line 498, in makeAgentCaseReportFilename
return self.cleanForFilename(agentId) + "_case_" + c + "." + ext
File "~/wstest/lib/python2.7/site-packages/autobahntestsuite/fuzzing.py", line 487, in cleanForFilename
s0 = ''.join([c if c in "abcdefghjiklmnopqrstuvwxyz0123456789" else " " for c in str.strip().lower()])
exceptions.AttributeError: 'NoneType' object has no attribute 'strip'
```

**Comment by oberstet** [comment]
well, then don't redirect;) wont fix
