### ISSUE TITLE
Problem to run the docker container

### ISSUE THREAD

**Issue by lohmanndouglas** [crossbario/autobahn-testsuite#84]
I am having a problem to run the docker container, wstest cannot find the file '/config/fuzzingserver.json'.

- OS: ArchLinux
- Docker version 18.05.0-ce, build f150324782

Following the command and the output:

> ➜  ~ **docker run -it --rm -v ${PWD}/config:/config -v ${PWD}/reports:/reports -p 9001:9001 --name fuzzingserver crossbario/autobahn-testsuite**
Unable to find image 'crossbario/autobahn-testsuite:latest' locally
latest: Pulling from crossbario/autobahn-testsuite
4176fe04cefe: Pull complete 
851356ecf618: Pull complete 
6115379c7b49: Pull complete 
aaf7d781d601: Pull complete 
40cf661a3cc4: Pull complete 
c4c5361383ef: Pull complete 
fd2f62987dc6: Pull complete 
f4c8fbf7c040: Pull complete 
717bb23d85ca: Pull complete 
Digest: sha256:5b204b2e97020488f00650d8c55a7c597db77399d840914937a6d2674c6b8631
Status: Downloaded newer image for crossbario/autobahn-testsuite:latest
Using explicit spec file '/config/fuzzingserver.json'
Loading spec from /config/fuzzingserver.json
Traceback (most recent call last):
  File "/usr/local/bin/wstest", line 11, in <module>
    sys.exit(run())
  File "/usr/local/site-packages/autobahntestsuite/wstest.py", line 337, in run
    spec = json.loads(open(spec_filename).read())
IOError: [Errno 2] No such file or directory: '/config/fuzzingserver.json'

Am I doing something wrong?
Grateful for any answer

**Comment by sdvdxl** [comment]
you need create file `config/fuzzingserver.json` in `pwd`
